# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 26 Marathons
email: julia.mitchelmore@gmail.com
description: > 
  Julia's personal challenge to run 26.2 marathons by age 26.2,
  while raising funds for Trekstock UK and the Australian Heart Foundation
baseurl: ""
url: "http://26marathons.com"
twitter_username: mitchelmore_j
github_username:  juliamitchelmore

# Build settings
markdown: kramdown

# Outputting
permalink: /:title